const common = {

    //PATIENTS_API start here
    GET_PATIENTS_API: 'GET_PATIENTS_API',
    ADD_PATIENT_API: 'ADD_PATIENT_API',
    //PATIENTS_API end here

    // OPERATION APIS start here
    GET_OPERATION_THEATER_API: 'GET_OPERATION_THEATER_API',
    GET_OPERATION_ROOMS_API: 'GET_OPERATION_ROOMS_API',

    GET_ALL_OPERATIONS_API: 'GET_ALL_OPERATIONS_API',
    UPDATE_OPERATION_API: 'UPDATE_OPERATION_API',
    CREATE_OPERATION_API: 'CREATE_OPERATION_API',
    //OPERATION APIS end here

    //GET_DIAGNOSIS start here
    GET_DIAGNOSIS_API: 'GET_DIAGNOSIS_API',
    //GET_DIAGNOSIS end here

    //GET_PROCEDURES start here
    GET_PROCEDURES_API: 'GET_PROCEDURES_API',
    //GET_PROCEDURES end here

};

export default common;